//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juega.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancha_Horario_Dia
    {
        public Cancha_Horario_Dia()
        {
            this.Cancha_Horario_Dia_Hora = new HashSet<Cancha_Horario_Dia_Hora>();
        }
    
        public long IdCancha_Horario_Dia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TipoEstado { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<long> IdCancha { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        public virtual Cancha Cancha { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Cancha_Horario_Dia_Hora> Cancha_Horario_Dia_Hora { get; set; }
    }
}
