//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juega.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancha_Horario_Dia_Hora
    {
        public Cancha_Horario_Dia_Hora()
        {
            this.Cancha_Reservacion = new HashSet<Cancha_Reservacion>();
        }
    
        public long IdCancha_Horario_Dia_Hora { get; set; }
        public Nullable<System.DateTime> HoraDesde { get; set; }
        public Nullable<System.DateTime> HoraHasta { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string TipoEstado { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<long> IdCancha_Horario_Dia { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        public virtual Cancha_Horario_Dia Cancha_Horario_Dia { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Cancha_Reservacion> Cancha_Reservacion { get; set; }
    }
}
