//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juega.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancha_Valoracion
    {
        public long IdCancha_Valoracion { get; set; }
        public Nullable<int> Valoracion { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<long> IdCancha { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        public virtual Cancha Cancha { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
