//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juega.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplejoDeportivo
    {
        public ComplejoDeportivo()
        {
            this.Cancha = new HashSet<Cancha>();
        }
    
        public long IdComplejoDeportivo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public string Coodernadas { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        public virtual ICollection<Cancha> Cancha { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
