//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juega.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Cancha = new HashSet<Cancha>();
            this.Cancha_Foto = new HashSet<Cancha_Foto>();
            this.Cancha_Horario_Dia = new HashSet<Cancha_Horario_Dia>();
            this.Cancha_Horario_Dia_Hora = new HashSet<Cancha_Horario_Dia_Hora>();
            this.Cancha_Reservacion = new HashSet<Cancha_Reservacion>();
            this.Cancha_Valoracion = new HashSet<Cancha_Valoracion>();
            this.ComplejoDeportivo = new HashSet<ComplejoDeportivo>();
            this.Denuncia = new HashSet<Denuncia>();
            this.Denuncia1 = new HashSet<Denuncia>();
            this.Denuncia2 = new HashSet<Denuncia>();
            this.Equipo = new HashSet<Equipo>();
            this.Equipo_Foto = new HashSet<Equipo_Foto>();
            this.Equipo_Jugador = new HashSet<Equipo_Jugador>();
            this.Equipo_Tecnico = new HashSet<Equipo_Tecnico>();
            this.Equipo_Valoracion = new HashSet<Equipo_Valoracion>();
            this.Reto = new HashSet<Reto>();
            this.Token = new HashSet<Token>();
            this.Usuario_Valoracion = new HashSet<Usuario_Valoracion>();
            this.Usuario_Solicitud_Equipo = new HashSet<Usuario_Solicitud_Equipo>();
            this.Usuario_Solicitud_AdminCancha = new HashSet<Usuario_Solicitud_AdminCancha>();
            this.Usuario_Valoracion1 = new HashSet<Usuario_Valoracion>();
            this.Usuario_Foto = new HashSet<Usuario_Foto>();
            this.Usuario_Registro_Acceso = new HashSet<Usuario_Registro_Acceso>();
        }
    
        public long IdUsuario { get; set; }
        public string IdUsuarioSeguridad { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Correo { get; set; }
        public string Telefonos { get; set; }
        public string TipoEstado { get; set; }
        public Nullable<decimal> Valoracion { get; set; }
        public Nullable<bool> EsEspectador { get; set; }
        public Nullable<bool> EsAdminCancha { get; set; }
        public Nullable<bool> EsAdminEquipo { get; set; }
        public Nullable<bool> EsJugador { get; set; }
        public string Descripcion { get; set; }
        public string FotoPrincipal { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual ICollection<Cancha> Cancha { get; set; }
        public virtual ICollection<Cancha_Foto> Cancha_Foto { get; set; }
        public virtual ICollection<Cancha_Horario_Dia> Cancha_Horario_Dia { get; set; }
        public virtual ICollection<Cancha_Horario_Dia_Hora> Cancha_Horario_Dia_Hora { get; set; }
        public virtual ICollection<Cancha_Reservacion> Cancha_Reservacion { get; set; }
        public virtual ICollection<Cancha_Valoracion> Cancha_Valoracion { get; set; }
        public virtual ICollection<ComplejoDeportivo> ComplejoDeportivo { get; set; }
        public virtual ICollection<Denuncia> Denuncia { get; set; }
        public virtual ICollection<Denuncia> Denuncia1 { get; set; }
        public virtual ICollection<Denuncia> Denuncia2 { get; set; }
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual ICollection<Equipo_Foto> Equipo_Foto { get; set; }
        public virtual ICollection<Equipo_Jugador> Equipo_Jugador { get; set; }
        public virtual ICollection<Equipo_Tecnico> Equipo_Tecnico { get; set; }
        public virtual ICollection<Equipo_Valoracion> Equipo_Valoracion { get; set; }
        public virtual ICollection<Reto> Reto { get; set; }
        public virtual ICollection<Token> Token { get; set; }
        public virtual ICollection<Usuario_Valoracion> Usuario_Valoracion { get; set; }
        public virtual ICollection<Usuario_Solicitud_Equipo> Usuario_Solicitud_Equipo { get; set; }
        public virtual ICollection<Usuario_Solicitud_AdminCancha> Usuario_Solicitud_AdminCancha { get; set; }
        public virtual ICollection<Usuario_Valoracion> Usuario_Valoracion1 { get; set; }
        public virtual ICollection<Usuario_Foto> Usuario_Foto { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<Usuario_Registro_Acceso> Usuario_Registro_Acceso { get; set; }
    }
}
