//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juega.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Valoracion
    {
        public long IdUsuario_Valoracion { get; set; }
        public string Titulo { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> Valoracion { get; set; }
        public Nullable<long> IdUsuarioValora { get; set; }
        public Nullable<long> IdUsuarioValorado { get; set; }
        public Nullable<System.DateTime> FechaCreo { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
